In [5]:
import torch

#**Tensor Initialization**

In [ ]:

device = "cuda" if torch.cuda.is_available() else "cpu"

torch_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32, device = device, requires_grad = True)
print(torch_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [ ]:
X1 = torch.empty((2,2)),
print("type of X1 is:",X1)

X2 = torch.rand((2,2))
print("type of X2 is:",X2)

X3 = torch.empty((2,2)).uniform_(0,1)
print("type of X3 is:",X3)

X4 = torch.ones((2,2))
print("type of X4 is:",X4)

X5 = torch.zeros((2,2))
print("type of X5 is:",X5)

X6 = torch.eye(2,2)
print("type of X6 is:",X6)

X7 = torch.diag(torch.ones((2)))
print("type of X7 is:",X7)

X8 = torch.arange(start=0,end=5, step=1)
print("type of X8 is:",X8)

X9 = torch.linspace(start=0.1, end=1, steps=10)
print("type of X9 is:",X9)

type of X1 is: (tensor([[1.2911e+09, 3.0914e-41],
        [1.2964e+09, 3.0914e-41]]),)
type of X2 is: tensor([[0.9608, 0.8533],
        [0.2109, 0.1900]])
type of X3 is: tensor([[0.3165, 0.1189],
        [0.4185, 0.7467]])
type of X4 is: tensor([[1., 1.],
        [1., 1.]])
type of X5 is: tensor([[0., 0.],
        [0., 0.]])
type of X6 is: tensor([[1., 0.],
        [0., 1.]])
type of X7 is: tensor([[1., 0.],
        [0., 1.]])
type of X8 is: tensor([0, 1, 2, 3, 4])
type of X9 is: tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [ ]:
X1 = torch.empty(5,5) # dtype = int-32
print("type of X1 is:", X1.dtype)

X2 = X1.bool()            # Convert into binary form
print("type of X2 is:",X2.dtype)

X3 = X1.short()           # Convert into dtype int-16
print("type of X3 is:",X3.dtype)

X4 = X1.long()            # Convert into dtype int-64
print("type of X4 is:",X4.dtype)

X5 = X1.half()            # Convert into dtype float-16
print("type of X5 is:",X5.dtype)

X6 = X1.float()           # Convert into dtype float-32
print("type of X6 is:",X6.dtype)

X7 = X1.double()          # Convert into dtype float-64
print("type of X7 is:",X7.dtype)

type of X1 is: torch.float32
type of X2 is: torch.bool
type of X3 is: torch.int16
type of X4 is: torch.int64
type of X5 is: torch.float16
type of X6 is: torch.float32
type of X7 is: torch.float64


# **Tensor Maths**

In [ ]:
X1 = torch.tensor([1,2,3])
X2 = torch.tensor([4,5,6])

#Addition:
Z = X1 + X2
Z = torch.add(X1, X2)
print("Addition is:",Z)

#Inplace operation:
X2 += X1
print("Addition inplace is:", X2)

X1 = torch.tensor([1,2,3])
X2 = torch.tensor([4,5,6])
X2 = X2.add(X1)
print("Addition inplace is:", X2)

#Subraction:
Z = X1 - X2
print("The subraction is:",Z)

#Division:
Z = torch.true_divide( X1, X2)
print("The division is:",Z)

#Exponential:
Z = X1.pow(2)
Z = X1 ** 2
print(Z)


Addition is: tensor([5, 7, 9])
Addition inplace is: tensor([5, 7, 9])
Addition inplace is: tensor([5, 7, 9])
The subraction is: tensor([-4, -5, -6])
The division is: tensor([0.2000, 0.2857, 0.3333])
tensor([1, 4, 9])


In [ ]:
X1 = torch.tensor([[1,2,3],[1,2,3]])
X2 = torch.tensor([[1,2],[1,2],[1,2]])

#Metrix Multiplication:
Z = torch.mm(X1, X2)
print("The product is:",Z)
Z = X1.mm(X2)
print("The product is:",Z)

#Element-wise Multiplication:
X1 = torch.tensor([1,2,3])
X2 = torch.tensor([1,2,3])
Z = X1 * X2
print("The element-wise product is:", Z)

#Dot product:
Z = torch.dot(X1, X2)
print("The dot product is:",Z)

#Batch Metrix Multiplication:
batch = 2
a = 3
b = 5
c = 4
X1 = torch.rand((batch, a, b))
X2 = torch.rand((batch, b, c))
Z = torch.bmm(X1,X2)
print("The product os batch multiplication is:",Z.shape)

The product is: tensor([[ 6, 12],
        [ 6, 12]])
The product is: tensor([[ 6, 12],
        [ 6, 12]])
The element-wise product is: tensor([1, 4, 9])
The dot product is: tensor(14)
The product os batch multiplication is: torch.Size([2, 3, 4])


In [ ]:
X1 = torch.tensor([1,2,3])
X2 = torch.tensor([4,5,6])
indices, values = torch.max(X1, dim=0)
print("The indice and value is:", (indices, values))
indices = torch.argmax(X1, dim=0)
print("The indice is:", indices)

The indice and value is: (tensor(3), tensor(2))
The indice is: tensor(2)


## **Tensor Indexing**

In [7]:
batch_size = 2
features = 5
x = torch.rand(batch_size, features)
z = x[0].shape     # Get the shape of first tensor
print(z)
z = x[:,0].shape   # Get the shape of all tensors at the first dimension
print(z)

#Conditional Formatting:
Z = torch.arange(10)
Z1 = Z[(Z>2) | (Z<8)]     # Get the elements greater than 2 and less than 8
print(Z1)
Z2 = Z[Z.remainder(2)==0] # Get the even numbered elements
print(Z2)
Z3 = torch.where(Z2>5, Z2, Z2*2)
print(Z3)

torch.Size([5])
torch.Size([2])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])
tensor([0, 4, 8, 6, 8])


## **Tensor Reshaping**

In [8]:
X = torch.tensor([1,2,3,4])
Z = X.view(2,2)    # When X is Contiguous
print(Z)
Z = X.reshape(2,2) # Idependent of Contiguous nature of X
print(Z)

SyntaxError: invalid syntax (<ipython-input-8-82232c4e4378>, line 4)

In [19]:
#Concatenation:
X1 = torch.rand([2,4])
X2 = torch.rand([2,4])
Z1 = torch.cat((X1, X2), dim=0)
print(Z1)
Z2 = torch.cat((X1, X2), dim=1)
print(Z2)
T = torch.tensor([1,2,3])
print(T.shape)
T = T.view(1, 3)
T = T.permute((1,0))
print(T.shape)
T = T.unsqueeze(0)
print(T.shape)

tensor([[0.3916, 0.5857, 0.0410, 0.6214],
        [0.8613, 0.4667, 0.3718, 0.6619],
        [0.2342, 0.4413, 0.3764, 0.6481],
        [0.4940, 0.1315, 0.9211, 0.3626]])
tensor([[0.3916, 0.5857, 0.0410, 0.6214, 0.2342, 0.4413, 0.3764, 0.6481],
        [0.8613, 0.4667, 0.3718, 0.6619, 0.4940, 0.1315, 0.9211, 0.3626]])
torch.Size([3])
torch.Size([3, 1])
torch.Size([1, 3, 1])
